# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker
  pool: Azure
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'docker'
        repository: 'drapo/docs'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: latest
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'docker push drapo/docs'