name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner  }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./src
        push: true
        file: ./src/Dockerfile
        tags: ghcr.io/spadrapo/docs:latest
        
    - name: Webhook Action
    # You may pin to the exact commit or the version.
    # uses: joelwmale/webhook-action@448a17bf857ead98546cfbdbe3b9d4cf979dda95
      uses: joelwmale/webhook-action@2.3.2
      with:
       # The url to send the webhook event to
        url: https://$drapo:gmWy6LNRxiKCYnBquToAZrobCTGbfb36snZ8G89iiuFLwtRusQrTxA6pJ8yz@drapo.scm.azurewebsites.net/api/registry/webhook
